language: ruby
sudo: false
cache: bundler

rvm:
  - 3.0.0

env:
  - DB=mysql DATABASE_URL="mysql2://root@127.0.0.1:3306/territory_manager_test"
  - DB=pg DATABASE_URL="postgres://postgres@localhost:5432/territory_manager_ENV"

before_script:
  - psql -c 'create database territory_manager_test;' -U postgres
  - mysql -e 'CREATE DATABASE territory_manager_test;'
  - bundle exec rake db:migrate

script:
  - RAILS_ENV=test bundle exec rspec
  - bundle exec rubocop --version
  - bundle exec rubocop -a

services:
  - mysql

addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
