# Some nubmers were taken from books:https://catholic-resources.org/Bible/OT-Statistics-NAB.htm
  - name: Genesis
    chapters: 50
    verses:
      1: 31
      2: 25
      3: 24
      4: 26
      5: 32
      6: 22
      7: 24
      8: 22
      9: 29
      10: 32
      11: 32
      12: 20
      13: 18
      14: 24
      15: 21
      16: 16
      17: 27
      18: 33
      19: 38
      20: 18
      21: 34
      22: 24
      23: 20
      24: 67
      25: 34
      26: 35
      27: 46
      28: 22
      29: 35
      30: 43
      31: 54
      32: 33
      33: 20
      34: 31
      35: 29
      36: 43
      37: 36
      38: 30
      39: 23
      40: 23
      41: 57
      42: 38
      43: 34
      44: 34
      45: 28
      46: 34
      47: 31
      48: 22
      49: 33
      50: 26
  - name: Exodus
    chapters: 40
    verses:
      1: 22
      2: 25
      3: 22
      4: 31
      5: 23
      6: 30
      7: 29
      8: 28
      9: 35
      10: 29
      11: 10
      12: 51
      13: 22
      14: 31
      15: 27
      16: 36
      17: 16
      18: 27
      19: 25
      20: 26
      21: 37
      22: 30
      23: 33
      24: 18
      25: 40
      26: 37
      27: 21
      28: 43
      29: 46
      30: 38
      31: 18
      32: 35
      33: 23
      34: 35
      35: 35
      36: 38
      37: 29
      38: 31
      39: 43
      40: 38
  - name: Leviticus
    chapters: 27
    verses:
      1: 17
      2: 16
      3: 17
      4: 35
      5: 26
      6: 23
      7: 38
      8: 36
      9: 24
      10: 20
      11: 47
      12: 8
      13: 59
      14: 57
      15: 33
      16: 34
      17: 16
      18: 30
      19: 37
      20: 27
      21: 24
      22: 33
      23: 44
      24: 23
      25: 55
      26: 46
      27: 34
  - name: Numbers
    chapters: 36
    verses:
      1: 54
      2: 34
      3: 51
      4: 49
      5: 31
      6: 27
      7: 89
      8: 26
      9: 23
      10: 36
      11: 35
      12: 16
      13: 33
      14: 45
      15: 41
      16: 35
      17: 28
      18: 32
      19: 22
      20: 29
      21: 35
      22: 41
      23: 30
      24: 25
      25: 19
      26: 65
      27: 23
      28: 31
      29: 39
      30: 17
      31: 54
      32: 42
      33: 56
      34: 29
      35: 34
      36: 13
  - name: Deuteronomy
    chapters: 34
    verses:
      1: 46
      2: 37
      3: 29
      4: 49
      5: 33
      6: 25
      7: 26
      8: 20
      9: 29
      10: 22
      11: 32
      12: 31
      13: 19
      14: 29
      15: 23
      16: 22
      17: 20
      18: 22
      19: 21
      20: 20
      21: 23
      22: 29
      23: 26
      24: 22
      25: 19
      26: 19
      27: 26
      28: 69
      29: 28
      30: 20
      31: 30
      32: 52
      33: 29
      34: 12
  - name: Joshua
    chapters: 24
    verses:
      1: 18
      2: 24
      3: 17
      4: 24
      5: 15
      6: 27
      7: 26
      8: 35
      9: 27
      10: 43
      11: 23
      12: 24
      13: 33
      14: 15
      15: 63
      16: 10
      17: 18
      18: 28
      19: 51
      20: 9
      21: 45
      22: 34
      23: 16
      24: 33
  - name: Judges
    chapters: 21
    verses:
      1: 36
      2: 23
      3: 31
      4: 24
      5: 31
      6: 40
      7: 25
      8: 35
      9: 57
      10: 18
      11: 40
      12: 15
      13: 25
      14: 20
      15: 20
      16: 31
      17: 13
      18: 31
      19: 30
      20: 48
      21: 25
  - name: Ruth
    chapters: 4
    verses:
      1: 22
      2: 23
      3: 18
      4: 22
  - name: 1 Samuel
    chapters: 31
    verses:
      1: 28
      2: 36
      3: 21
      4: 22
      5: 12
      6: 21
      7: 17
      8: 22
      9: 27
      10: 27
      11: 15
      12: 25
      13: 23
      14: 52
      15: 35
      16: 23
      17: 58
      18: 30
      19: 24
      20: 42
      21: 16
      22: 23
      23: 28
      24: 23
      25: 43
      26: 25
      27: 12
      28: 25
      29: 11
      30: 31
      31: 13
  - name: 2 Samuel
    chapters: 24
    verses:
      1: 27
      2: 32
      3: 39
      4: 12
      5: 25
      6: 23
      7: 29
      8: 18
      9: 13
      10: 19
      11: 27
      12: 31
      13: 39
      14: 33
      15: 37
      16: 23
      17: 29
      18: 32
      19: 44
      20: 26
      21: 22
      22: 51
      23: 39
      24: 25
  - name: 1 Kings
    chapters: 22
    verses:
      1: 53
      2: 46
      3: 28
      4: 20
      5: 32
      6: 38
      7: 51
      8: 66
      9: 28
      10: 29
      11: 43
      12: 33
      13: 34
      14: 31
      15: 34
      16: 34
      17: 24
      18: 46
      19: 21
      20: 43
      21: 29
      22: 54
  - name: 2 Kings
    chapters: 25
    verses:
      1: 18
      2: 25
      3: 27
      4: 44
      5: 27
      6: 33
      7: 20
      8: 29
      9: 37
      10: 36
      11: 20
      12: 22
      13: 25
      14: 29
      15: 38
      16: 20
      17: 41
      18: 37
      19: 37
      20: 21
      21: 26
      22: 20
      23: 37
      24: 20
      25: 30
  - name: 1 Chronicles
    chapters: 29
    verses:
      1: 54
      2: 55
      3: 24
      4: 43
      5: 41
      6: 66
      7: 40
      8: 40
      9: 44
      10: 14
      11: 47
      12: 41
      13: 14
      14: 17
      15: 29
      16: 43
      17: 27
      18: 17
      19: 19
      20: 8
      21: 30
      22: 19
      23: 32
      24: 31
      25: 31
      26: 32
      27: 34
      28: 21
      29: 30
  - name: 2 Chronicles
    chapters: 36
    verses:
      1: 18
      2: 17
      3: 17
      4: 22
      5: 14
      6: 42
      7: 22
      8: 18
      9: 31
      10: 19
      11: 23
      12: 16
      13: 23
      14: 14
      15: 19
      16: 14
      17: 19
      18: 34
      19: 11
      20: 37
      21: 20
      22: 12
      23: 21
      24: 27
      25: 28
      26: 23
      27: 9
      28: 27
      29: 36
      30: 27
      31: 21
      32: 33
      33: 25
      34: 33
      35: 26
      36: 23
  - name: Ezra
    chapters: 10
    verses:
      1: 11
      2: 70
      3: 13
      4: 24
      5: 17
      6: 22
      7: 28
      8: 36
      9: 15
      10: 44
  - name: Nehemiah
    chapters: 13
    verses:
      1: 11
      2: 20
      3: 38
      4: 17
      5: 19
      6: 19
      7: 72
      8: 18
      9: 37
      10: 40
      11: 36
      12: 47
      13: 31
  - name: Esther
    chapters: 16
    verses:
      1: 22
      2: 23
      3: 15
      4: 17
      5: 14
      6: 14
      7: 10
      8: 17
      9: 32
      10: 3
      # 11: 17
      # 12: 8
      # 13: 30
      # 14: 16
      # 15: 24
      # 16: 10
  - name: Job
    chapters: 42
    verses:
      1: 22
      2: 13
      3: 26
      4: 21
      5: 27
      6: 30
      7: 21
      8: 22
      9: 35
      10: 22
      11: 20
      12: 25
      13: 28
      14: 22
      15: 35
      16: 22
      17: 16
      18: 21
      19: 29
      20: 29
      21: 34
      22: 30
      23: 17
      24: 25
      25: 6
      26: 14
      27: 21
      28: 28
      29: 25
      30: 31
      31: 40
      32: 22
      33: 33
      34: 37
      35: 16
      36: 33
      37: 24
      38: 41
      39: 30
      40: 32
      41: 26
      42: 17
  # TODO: Get number of verses in psalms
  # - name: Psalms (1-50)
  #   chapters: 0
  #   verses: {}
  # - name: Psalms (51-100)
  #   chapters: 0
  #   verses: {}
  - name: Proverbs
    chapters: 31
    verses:
      1: 33
      2: 22
      3: 35
      4: 27
      5: 23
      6: 35
      7: 27
      8: 36
      9: 18
      10: 32
      11: 31
      12: 28
      13: 25
      14: 35
      15: 33
      16: 33
      17: 28
      18: 24
      19: 29
      20: 30
      21: 31
      22: 29
      23: 35
      24: 34
      25: 28
      26: 28
      27: 27
      28: 28
      29: 27
      30: 33
      31: 31
  - name: Ecclesiastes
    chapters: 12
    verses:
      1: 18
      2: 26
      3: 22
      4: 17
      5: 19
      6: 12
      7: 29
      8: 17
      9: 18
      10: 20
      11: 10
      12: 14
  - name: Song of Solomon
    chapters: 8
    verses:
      1: 17
      2: 17
      3: 11
      4: 16
      5: 16
      6: 12
      7: 14
      8: 14
  - name: Isaiah
    chapters: 66
    verses:
      1: 31
      2: 22
      3: 26
      4: 6
      5: 30
      6: 13
      7: 25
      8: 23
      9: 20
      10: 34
      11: 16
      12: 6
      13: 22
      14: 32
      15: 9
      16: 14
      17: 14
      18: 7
      19: 25
      20: 6
      21: 17
      22: 25
      23: 18
      24: 23
      25: 12
      26: 21
      27: 13
      28: 29
      29: 24
      30: 33
      31: 9
      32: 20
      33: 24
      34: 17
      35: 10
      36: 22
      37: 38
      38: 22
      39: 8
      40: 31
      41: 29
      42: 25
      43: 28
      44: 28
      45: 25
      46: 13
      47: 15
      48: 22
      49: 26
      50: 11
      51: 23
      52: 15
      53: 12
      54: 17
      55: 13
      56: 12
      57: 21
      58: 14
      59: 21
      60: 22
      61: 11
      62: 12
      63: 19
      64: 11
      65: 25
      66: 24
  - name: Jeremiah
    chapters: 52
    verses:
      1: 19
      2: 37
      3: 25
      4: 31
      5: 31
      6: 30
      7: 34
      8: 23
      9: 25
      10: 25
      11: 23
      12: 17
      13: 27
      14: 22
      15: 21
      16: 21
      17: 27
      18: 23
      19: 15
      20: 18
      21: 14
      22: 30
      23: 40
      24: 10
      25: 38
      26: 24
      27: 22
      28: 17
      29: 32
      30: 24
      31: 40
      32: 44
      33: 26
      34: 22
      35: 19
      36: 32
      37: 21
      38: 28
      39: 18
      40: 16
      41: 18
      42: 22
      43: 13
      44: 30
      45: 5
      46: 28
      47: 7
      48: 47
      49: 39
      50: 46
      51: 64
      52: 34
  - name: Lamentations
    chapters: 5
    verses:
      1: 22
      2: 22
      3: 66
      4: 22
      5: 22
  - name: Ezekiel
    chapters: 48
    verses:
      1: 28
      2: 10
      3: 27
      4: 17
      5: 17
      6: 14
      7: 27
      8: 18
      9: 11
      10: 22
      11: 25
      12: 28
      13: 23
      14: 23
      15: 8
      16: 63
      17: 24
      18: 32
      19: 14
      20: 44
      21: 37
      22: 31
      23: 49
      24: 27
      25: 17
      26: 21
      27: 36
      28: 26
      29: 21
      30: 26
      31: 18
      32: 32
      33: 33
      34: 31
      35: 15
      36: 38
      37: 28
      38: 23
      39: 29
      40: 49
      41: 26
      42: 20
      43: 27
      44: 31
      45: 25
      46: 24
      47: 23
      48: 35
  - name: Daniel
    chapters: 14
    verses:
      1: 21
      2: 49
      3: 100
      4: 34
      5: 30
      6: 29
      7: 28
      8: 27
      9: 27
      10: 21
      11: 45
      12: 13
      # 13: 64
      # 14: 42
  - name: Hosea
    chapters: 14
    verses:
      1: 9
      2: 25
      3: 5
      4: 19
      5: 15
      6: 11
      7: 16
      8: 14
      9: 17
      10: 15
      11: 11
      12: 15
      13: 15
      14: 10
  - name: Joel
    chapters: 4
    verses:
      1: 20
      2: 27
      3: 5
      4: 21
  - name: Amos
    chapters: 9
    verses:
      1: 15
      2: 16
      3: 15
      4: 13
      5: 27
      6: 14
      7: 17
      8: 14
      9: 15
  - name: Obadiah
    chapters: 1
    verses:
      1: 21
  - name: Jonah
    chapters: 4
    verses:
      1: 16
      2: 11
      3: 10
      4: 11
  - name: Micah
    chapters: 7
    verses:
      1: 16
      2: 13
      3: 12
      4: 14
      5: 14
      6: 16
      7: 20
  - name: Nahum
    chapters: 3
    verses:
      1: 14
      2: 14
      3: 19
  - name: Habakkuk
    chapters: 3
    verses:
      1: 17
      2: 20
      3: 19
  - name: Zephaniah
    chapters: 3
    verses:
      1: 18
      2: 15
      3: 20
  - name: Haggai
    chapters: 2
    verses:
      1: 15
      2: 23
  - name: Zechariah
    chapters: 14
    verses:
      1: 17
      2: 17
      3: 10
      4: 14
      5: 11
      6: 15
      7: 14
      8: 23
      9: 17
      10: 12
      11: 17
      12: 14
      13: 9
      14: 21
  - name: Malachi
    chapters: 3
    verses:
      1: 14
      2: 17
      3: 24
