name: Rails Unit Tests
on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - '*'
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:12.5
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          ALLOW_IP_RANGE: 0.0.0.0/0
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
    - name: Build and test with Rake
      env:
        RAILS_ENV: test
        DATABASE_URL: "postgres://postgres:postgres@localhost:5432/khtest_test"
      run: |
        sudo apt-get -yqq install libpq-dev
        yarn install
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rails db:create
        bundle exec rails db:migrate
        ./bin/rspec
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
